allows you to manually trigger a workflow run

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,8 @@ on:
     branches: [ "master", "develop" ]
   pull_request:
     branches: [ "master", "develop" ]
-
+  workflow_dispatch:
+  
 jobs:
   build:
 
@@ -18,21 +19,37 @@ jobs:
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
 
-      - name: Display .NET version
-        run: dotnet --version
+#      - name: Display .NET version
+#        run: dotnet --version
 
-      - name: Set VERSION variable from tag
-        run: echo "VERSION=0.0.0" >> $GITHUB_ENV
+      - name: Set VERSION variable from tag or latest release
+        shell: pwsh
+        run: |
+          $env:VERSION = $env:GITHUB_REF -replace '^refs/tags/', ''
+          if ([string]::IsNullOrEmpty($env:VERSION)) {
+            Write-Host "Tag not found. Getting latest release..."
+            $env:VERSION = gh release list --limit 1 --json tagName --jq '.[0].tagName'
+          }
+          
+          if ([string]::IsNullOrEmpty($env:VERSION)) {
+            Write-Error "Error: VERSION is empty."
+            exit 1
+          } else {
+            Write-Host "VERSION: $env:VERSION"
+            echo "VERSION=$env:VERSION" >> $env:GITHUB_ENV
+          }
+        env:
+          GITHUB_REF: ${{ github.ref }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
 
       - name: Download References
         shell: pwsh
-        run: |
-          .\Download-References.ps1
+        run: .\Download-References.ps1
 
-      - name: Build DLLs - Oxide
-        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Oxide /p:Version=$VERSION /p:BuildServer=Github -f net48
+      - name: Build DLL (Oxide)
+        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Oxide /p:Version=$env:VERSION /p:BuildServer=Github -f net48
         working-directory: Oxide.Ext.Discord
 
-      - name: Build DLLs - Carbon
-        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Carbon /p:Version=$VERSION /p:BuildServer=Github -f net48
+      - name: Build DLL (Carbon)
+        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Carbon /p:Version=$env:VERSION /p:BuildServer=Github -f net48
         working-directory: Oxide.Ext.Discord
