Don't build carbon for now

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -5,7 +5,7 @@ on:
     tags:
       - "[0-9]+.[0-9]+.[0-9]+-preview.[0-9]+.[0-9]+.[0-9]"
   workflow_dispatch:
-    
+
 jobs:
   build:
 
@@ -24,14 +24,15 @@ jobs:
       - name: Set VERSION variable from tag or latest release
         shell: pwsh
         run: |
-          $env:VERSION = $env:GITHUB_REF -replace '^refs/tags/', ''
-          if ([string]::IsNullOrEmpty($env:VERSION)) {
-            Write-Host "Tag not found. Getting latest release..."
-            $env:VERSION = gh release list --limit 1 --json tagName --jq '.[0].tagName'
-          }
-          
+          $env:VERSION = gh release list --limit 1 --json tagName --jq '.[0].tagName'
           if ([string]::IsNullOrEmpty($env:VERSION)) {
             Write-Error "Error: VERSION is empty."
+            exit 1
+          }
+
+          $versionPattern = '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z\-\.]+)?(\+[0-9A-Za-z\-\.]+)?$'
+          if ($env:VERSION -notmatch $versionPattern) {
+            Write-Error "Error: VERSION is not a valid Semantic Version (https://semver.org)."
             exit 1
           } else {
             Write-Host "VERSION: $env:VERSION"
@@ -39,7 +40,7 @@ jobs:
           }
         env:
           GITHUB_REF: ${{ github.ref }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Download References
         shell: pwsh
@@ -49,12 +50,11 @@ jobs:
         run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Oxide /p:Version=$env:VERSION /p:BuildServer=Github -f net48
         working-directory: Oxide.Ext.Discord
 
-      - name: Build DLL (Carbon)
-        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Carbon /p:Version=$env:VERSION /p:BuildServer=Github -f net48
-        working-directory: Oxide.Ext.Discord
+#      - name: Build DLL (Carbon)
+#        run: dotnet build Oxide.Ext.Discord.csproj -c Release /p:Platform=Carbon /p:Version=$env:VERSION /p:BuildServer=Github -f net48
+#        working-directory: Oxide.Ext.Discord
 
       - name: Upload Release Assets
-        run: gh release upload $env:VERSION Oxide.Ext.Discord/bin/Oxide/Release/net48/Oxide.Ext.Discord.dll Oxide.Ext.Discord/bin/Carbon/Release/net48/Carbon.Discord.dll --clobber
+        run: gh release upload --clobber $env:VERSION Oxide.Ext.Discord/bin/Oxide/Release/net48/Oxide.Ext.Discord.dll #Oxide.Ext.Discord/bin/Carbon/Release/net48/Carbon.Discord.dll
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    
